[workspace]
resolver = "3"
members = [
    "core",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha3 = "0.10"