[package]
name = "treasure-hunt-core"
version.workspace = true
edition.workspace = true

[features]
default = []
test-only = []

[dependencies]
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true